# Generated by Django 3.1.2 on 2020-10-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='featured',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='summery',
            field=models.TextField(blank=True, null=True),
        ),
    ]
